[package]
name = "aco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
random_choice = "0.3.2"
once_cell = "1.17.1"